version: "3.8"

services:
  app:
    build: .
    entrypoint: ./.docker/entrypoint.sh
    volumes:
      - .:/home/node/app
    ports:
      - "3000:3000"
    environment:
      - DBHOST=db
      - REDIS_URL=redis:6379
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    links:
      - db
      - redis
    network_mode: "bridge"

  db:
    container_name: "reddit_api_db"
    build: .docker/postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=reddit_api
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    network_mode: "bridge"

  redis:
    image: redis
    command: redis-server --requirepass dockerRedis
    ports:
      - "6379:6379"
    volumes:
      - .redis:/data
    network_mode: "bridge"
